### ISSUE TITLE
some t letters look like an s in Safari 

### ISSUE THREAD

**Issue by rmglennon** [mapzen/metro-extracts#264]
I noticed this on the page to choose the boundaries of the custom extract. The actual text is definitely "the" and it's only this "the" that has this problem! The "the" in the next sentence looks OK, but this one is always she on Safari.

Step 1: Confirm ​she boundaries...

![image](https://cloud.githubusercontent.com/assets/4380498/17571140/d0d89f44-5f03-11e6-9671-93b1ea02e02c.png)

**Comment by binx** [comment]
confirm I see this on safari as well.
so... I think this is a bug in the Open Sans webfont. I tried different treatments in the browser (font-size, font-style, font-weight) and it's all still rendering as an s.

@souperneon @migurski thoughts?  We use this typeface all over the site... this is the only instance I've seen of this happening, but it does definitely look like a typo...

**Comment by louh** [comment]
Oooooh. What you have here is a sneaky invisible Unicode control character problem!

There's something _weird_ here:

![screenshot 2016-08-11 12 24 12](https://cloud.githubusercontent.com/assets/2553268/17596258/8fb42306-5fbe-11e6-8f06-658b0fe7275c.png)

(You can use an invisible character plugin / option in your text editor to show these.)

I was curious what it was, so I pasted a few characters around it into [unicodelookup.com](http://unicodelookup.com/#m ​t/1):

![screenshot 2016-08-11 12 28 40](https://cloud.githubusercontent.com/assets/2553268/17596386/277bbf96-5fbf-11e6-89c3-c3382336086f.png)

Everything there is what we'd expect, but then there's that zero-width space character. You definitely don't need that there! And for whatever reason, a zero-width space character plus a letter `t` causes Safari to render it as an `s` (ligatures bug?)

Anyway, try this for a quick fix: open the web developer console and delete the text, then retype it. You'll get the correct `the` because you're typing the letters you expect. So even though there's a weird font bug, it's easily fixable on our end.

**Comment by binx** [comment]
haha that's amazing. thanks @louh!

**Comment by rmglennon** [comment]
very nice sleuthing @louh! thanks for sharing.

**Comment by souperneon** [comment]
awesome @louh 👏
